# Generated by Django 4.0.4 on 2022-05-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='published',
        ),
    ]
