# Generated by Django 4.0.4 on 2022-05-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_remove_tutorial_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
